version: '3.1'

services:

  db:
    container_name: mysql8
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'posting'
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    volumes:
      - './volumes/mysql/default:/var/lib/mysql8'