spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true # SQL 출력
        format_sql: true # SQL 포맷팅
        highlight_sql: true # SQL 하이라이팅

  datasource:
    url: jdbc:mysql://localhost:3306/posting?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: debug # SQL 실행 로깅
    org.hibernate.orm.jdbc.bind: trace # JDBC 파라미터 바인딩 로깅
    org.hibernate.orm.jdbc.extract: trace # JDBC 결과 셋 추출 로깅
